# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\Desktop\vscode项目\python\QtTest\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentweigets import button


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(820, 449)
        Form.setMouseTracking(True)
        Form.setTabletTracking(False)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(200, 171, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = button(Form)
        self.pushButton.setGeometry(QtCore.QRect(360, 198, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox.setText(_translate("Form", "1"))
        self.pushButton.setText(_translate("Form", "PushButton"))
